// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sim_boss_loop
NumericMatrix sim_boss_loop(double mana, double mp5, NumericVector sb_dmg, LogicalVector sb_miss, LogicalVector sb_crit, LogicalVector curse_miss, double sb_mana, double lt_mana, double time);
RcppExport SEXP _warlockr_sim_boss_loop(SEXP manaSEXP, SEXP mp5SEXP, SEXP sb_dmgSEXP, SEXP sb_missSEXP, SEXP sb_critSEXP, SEXP curse_missSEXP, SEXP sb_manaSEXP, SEXP lt_manaSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mana(manaSEXP);
    Rcpp::traits::input_parameter< double >::type mp5(mp5SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sb_dmg(sb_dmgSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type sb_miss(sb_missSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type sb_crit(sb_critSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type curse_miss(curse_missSEXP);
    Rcpp::traits::input_parameter< double >::type sb_mana(sb_manaSEXP);
    Rcpp::traits::input_parameter< double >::type lt_mana(lt_manaSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(sim_boss_loop(mana, mp5, sb_dmg, sb_miss, sb_crit, curse_miss, sb_mana, lt_mana, time));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_warlockr_sim_boss_loop", (DL_FUNC) &_warlockr_sim_boss_loop, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_warlockr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
