# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate the Loop for a Boss Fight
#'
#' @inheritParams sim_boss_impl
sim_boss_loop <- function(mana, mp5, sb_dmg, sb_miss, sb_crit, curse_miss, sb_mana, lt_mana, time) {
    .Call(`_warlockr_sim_boss_loop`, mana, mp5, sb_dmg, sb_miss, sb_crit, curse_miss, sb_mana, lt_mana, time)
}

